### ISSUE TITLE
Can not install on Laravel 5.4

### ISSUE THREAD

**Issue by wangfei800** [joblocal/laravel-sqs-sns-subscription-queue#2]
This looks like a great package, however when I tried to install using composer command, I got error:
 [InvalidArgumentException]
  Could not find package joblocal/laravel-sqs-sns-subscription at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

My laravel is 5.4, and I also tried to add:
"minimum-stability": "dev",
to my composer.json

**Comment by jayhof** [comment]
I'm glad you're interested, thanks for reporting. It looks like my example install command in the readme file was missing "-queue". I have now added the missing part.
