### ISSUE TITLE
Subjects aren't guaranteed to be in SQS messages

### ISSUE THREAD

**Issue by spam-n-eggs** [joblocal/laravel-sqs-sns-subscription-queue#26]
I actually ran into this, a subjectless SQS Message, created by SNS via Textract.  I think we could replace 'Subject' in the Command with TopicArn in the event it doesn't exist.

If that's okay with you, I'll start putting together a PR.

**Comment by oldandgrey** [comment]
Yes, happy for you to use the TopicArn.

**Comment by juliusliebert** [comment]
Thanks for contributing, sorry for the late response!
New version 2.4.3 is created.
