### ISSUE TITLE
What is the "Subject" in the route mapping

### ISSUE THREAD

**Issue by p0kadevil** [joblocal/laravel-sqs-sns-subscription-queue#3]
Hello,

I followed your guide how to include this nice library here.
But I am a bit lost with the "routes" configuration. I have this:

'sqs' => [
            'driver' => 'sqs-sns',
            'key' => env('SQS_KEY'),
            'secret' => env('SQS_SECRET'),
            'prefix' => env('SQS_URL'),
            'queue' => env('SQS_NAME'),
            'region' => env('SQS_REGION'),
            'http' => [
                'timeout' => 1800,
                'connect_timeout' => 60,
            ],
            'routes' => [
                'elastic-transcoder-completed' => 'App\\Jobs\\ElasticTranscoderCompletedJob'
            ]
        ]

When an Elastic Transcoder Job finishes, it sends correct a message to my queue:

{
   "Type": "Notification",
   "MessageId": "d043aee8-7048-50b0-ba40-fc0aede57674",
   "TopicArn": "arn:aws:sns:eu-west-1:460112266754:elastic-transcoder-completed",
   "Subject": "Amazon Elastic Transcoder has finished transcoding job 1516804897281-01phxv.",
   "Message": {
      "state": "COMPLETED",
      "version": "2012-09-25",
      "jobId": "1516804897281-01phxv",
      "pipelineId": "...",
      "input": {
         "key": "tmp/1516804885138.mp4"
      },
      "inputCount": 1,
      "outputKeyPrefix": "...",
      "outputs": [...],
      "playlists": [...]
   },
   "Timestamp": "2018-01-24T14:42:53.158Z",
   "SignatureVersion": "1",
   "Signature": "...",
   "SigningCertURL": "...",
   "UnsubscribeURL": "..."
}

--> What exactly should I write in the "routes" config. Your tutorial says 'Subject'. But I cannot use the subject, since it is made dynamically as you can see. I tried with the topic name of SNS, but without luck.

Thanks in advance!

**Comment by jayhof** [comment]
Hello @p0kadevil, you are correct. This package assumes you have control over the "Subject" field. But it would be rather simple to modify this behaviour to check for the "TopicArn", have a look here: https://github.com/joblocal/laravel-sqs-sns-subscription-queue/blob/master/src/Queue/Jobs/SqsSnsJob.php#L40

I'm accepting pull requests ;)

**Comment by jayhof** [comment]
Hello @p0kadevil, I see your PR "changed Subject to TopicArn #4" where you replaced the functionality of using the Subject field. I'd like to keep this feature and extend this library to also allow for the routing via a TopicArn.

I had some free time so I created my own implementation of this feature. Please checkout "Variable route key (Subject, TopicArn) #5".

**Comment by jayhof** [comment]
I'll close this as the functionality was added in release 2.2 [v2.2 Enables routing via TopicArn](https://github.com/joblocal/laravel-sqs-sns-subscription-queue/releases/tag/v2.2)
