### ISSUE TITLE
Latest release stopped messages being sent to topic route

### ISSUE THREAD

**Issue by nickbryan** [joblocal/laravel-sqs-sns-subscription-queue#31]
Hi,

We recently updated our version of this package from 2.5 to 2.6 and now no messages are being consumed from our workers.

Our configuration is:
```
'connections' => [
        'sqs-sns' => [
            'driver' => 'sqs-sns',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'queue' => env('MY_EVENTS_SQS_QUEUE', 'your-queue-url'),
            'region' => env('AWS_DEFAULT_REGION', 'eu-west-2'),
            'routes' => [
                env('MY_EVENTS_SNS_TOPIC_ARN') => MyJob::class,
            ],
        ],
    ],
```

From looking at the [changes](https://github.com/joblocal/laravel-sqs-sns-subscription-queue/pull/30/files) it would seem that if a `Subject` is not set in the routes array then no messages will be processed thus breaking the functionality of allowing one job to listen for multiple messages from a topic by routing the topic to the job as described [here](https://github.com/joblocal/laravel-sqs-sns-subscription-queue#configuration).

**Comment by nickbryan** [comment]
I don't have context on why this change was made but isn't it already covered [here](https://github.com/joblocal/laravel-sqs-sns-subscription-queue/blob/master/src/Queue/Jobs/SqsSnsJob.php#L52)?

**Comment by btaskew** [comment]
I believe this was caused by https://github.com/joblocal/laravel-sqs-sns-subscription-queue/pull/30

The PR added a check to prevent unnecessary jobs from firing, however the newly added `routeExists` method only checks for the presence of a matching 'Subject' field and doesn't account for if you have only defined your route by 'TopicArn'. Therefore if you haven't defined a 'Subject' it won't ever fire the job as it can't find the matching route

**Comment by nickbryan** [comment]
Yeah, that is what I thought too 👍

**Comment by vixone** [comment]
> I don't have context on why this change was made but isn't it already covered [here](https://github.com/joblocal/laravel-sqs-sns-subscription-queue/blob/master/src/Queue/Jobs/SqsSnsJob.php#L52)?

As @btaskew correctly mentioned, we need to prevent unwanted messages (e.g. messages that we don't care about from a topic that receives multiple messages) from triggering the Job at all.
Triggering a job that has no handler causes the aws sdk Job class to throw an error.

With the last build, I added the same logic to check both Subject and Topic arn here.

**Comment by vixone** [comment]
see latest release.
