### ISSUE TITLE
Using this to dispatch job to SNS

### ISSUE THREAD

**Issue by GeniusGintaras** [joblocal/laravel-sqs-sns-subscription-queue#6]
Is it possible to use this package to dispatch a job to SNS, which would be tossed to SQS via SNS subscriptions?

I don't really get where and how SNS is used within this package.

**Comment by jayhof** [comment]
Hello @GeniusGintaras the purpose of this package is another one. With AWS SNS you can subscribe a SQS queue directly to a topic. All messages published in this way have a signature of:

`{
  "Type" : "Notification",
  "MessageId" : "63a3f6b6-d533-4a47-aef9-fcf5cf758c76",
  "TopicArn" : "arn:aws:sns:us-west-2:123456789012:MyTopic",
  "Subject" : "Testing publish to subscribed queues",
  "Message" : "Hello world!",
  "Timestamp" : "2017-03-29T05:12:16.901Z",
  "SignatureVersion" : "1",
  "Signature" : "...",
  "SigningCertURL" : "...",
  "UnsubscribeURL" : "..."
} `

Illuminate SqsJob cannot handle this type of message: https://laravel.com/api/5.5/Illuminate/Queue/Jobs/SqsJob.html

This package restructures the messages published via a SNS topic to a SQS queue to follow this form:

`{
  "job": "Illuminate\\Queue\\CallQueuedHandler@call",
  "data": {
    "commandName": "App\\Jobs\\YourJob",
    "command": "...",
  }
}`

I hope this cleared things up for you, I'll make sure to update the readme to better explain what's going on.

**Comment by GeniusGintaras** [comment]
That does sound exactly what I need, I just can't manage to make it work.

Am I correct saying that by using this driver, the traditional dispatch will send a message to SNS, and in turn it will end up in any subscribed queues in the format that you mentioned.
And before processing the job, this driver will parse the format and transform the message in queue to proper job structure?

If yes, then this is exactly what I need, just I can't make it work this way..

**Comment by jayhof** [comment]
Now I get your question, sorry.

> Am I correct saying that by using this driver, the traditional dispatch will send a message to SNS, and in turn it will end up in any subscribed queues in the format that you mentioned.

They way dispatch works is not touched by this package, it would still publish the message to a SQS queue.

What you can do is dispatching a SNS notification using the AWS SDK https://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.Sns.SnsClient.html#_publish subscribe your Queue(s) to the SNS-Topic.

This package will then create a processable job using either the "Subject" or "TopicArn" field to resolve a CommandName as described under "usage" in the readme. The contents of the SNS "Message" field are then passed along as a payload to your Job.


I use this package in a microservice architecture where multiple SQS queues are subscribed to the same topic. Each microservice has it's own SQS queue so it can fullfill it's concern whenever SNS receives a notification.

**Comment by GeniusGintaras** [comment]
Got it. Would be cool to extend it to publishing side as well, that it would publish the job payload to SNS topic.

**Comment by GeniusGintaras** [comment]
RIght, In what format SNS should receive the message then?
I'm trying to serialize new Jobs/ClassName(..) doesn't seem to work...

**Comment by jayhof** [comment]
Hello @GeniusGintaras, sorry for the wait. I updated the readme to explain better what's going on behind the scenes. I've also added examples. Let me know if I can assist further.

**Comment by GeniusGintaras** [comment]
Hey, no problems. 

The only issue is what exactly should you publish to SNS. 
It's just general usage of Notifiable, setup with SNS?

`$this->notify( ???? );`

I've tried serializing the job itself... to no avail.

Job class looks like this:
```
class Job implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $processor;

    /**
     * Create a new job instance.
     *
     * @param DataProcessor $processor Instance of assigned Data Processor
     * @internal param Match $match The match to process (assigned when constructing DataProcessor)
     */
    public function __construct(DataProcessor $processor)
    {
        $this->processor = $processor;
    }

    public function handle()
    {
        $this->processor->run();
    }
}
```

**Comment by jayhof** [comment]
Hello, so yeah again, this package really was built for microservices, where one service will publish an event to a SNS topic. Multiple other microservices then subscribe their SQS queues to this topic resulting in different jobs for each service.

We're explicitly not publishing a specific job to SNS here, instead what we're doing is delivering a json encoded payload within the message attribute of the SNS message.

SNS message is published to topic -> subscribed queues receive message -> SqsSnsConnector decodes queued SQS messages -> using the routes settings a matching Job instance is created and handled.

Thanks for your note about "YourJob", I will fix that in the readme.
