### ISSUE TITLE
Is there any functionality to send message from sns to sqs manually??

### ISSUE THREAD

**Issue by vicky-13** [joblocal/laravel-sqs-sns-subscription-queue#7]

**Comment by jayhof** [comment]
Hi @vicky-13 can you explain what you're trying to do?

If you want to do some manual testing you could use the AWS cli tools to publish to SNS:
https://docs.aws.amazon.com/cli/latest/reference/sns/publish.html

You could also publish via the AWS Console:
https://docs.aws.amazon.com/sns/latest/dg/PublishTopic.html

**Comment by vicky-13** [comment]
I have automation system in which third-party system sends data to SNS and then SNS publish that message to a mentioned queue and then I will get that sqs data using laravel job. But sns send data in a different format and laravel job don't understand this format.

SNS Format in sqs queue:
```
{
  "Type" : "Notification",
  "MessageId" : "63a3f6b6-d533-4a47-aef9-fcf5cf758c76",
  "TopicArn" : "arn:aws:sns:us-west-2:123456789012:MyTopic",
  "Subject" : "Testing publish to subscribed queues",
  "Message" : "Hello world!",
  "Timestamp" : "2017-03-29T05:12:16.901Z",
  "SignatureVersion" : "1",
  "Signature" : "...",
  "SigningCertURL" : "...",
  "UnsubscribeURL" : "..."
} ```

And laravel job undersatnd this format:
```
array (
  'displayName' => 'App\\Jobs\\SqsJobProcess',
  'job' => 'Illuminate\\Queue\\CallQueuedHandler@call',
  'maxTries' => NULL,
  'timeout' => NULL,
  'timeoutAt' => NULL,
  'data' => 
  array (
    'commandName' => 'App\\Jobs\\SqsJobProcess',
    'command' => 'O:18:"App\\Jobs\\SqsJobProcess":9:{s:7:"\\u0000*\\u0000uuid";s:36:"b65656af-8182-4e1e-9116-bd7a68a480a4";s:7:"\\u0000*\\u0000data";a:7:{s:4:"name";s:11:"Harlan Hess";s:4:"type";s:9:"Whitelist";s:11:"record_type";s:5:"Mixed";s:4:"info";a:2:{s:11:"description";s:86:"Ut voluptas autem quis excepteur totam magnam placeat necessitatibus consequatur culpa";s:5:"notes";s:98:"Impedit voluptatem adipisicing voluptas quo maiores tempora voluptas magnam eos nostrum eum fugiat";}s:13:"createNewList";s:4:"true";s:6:"header";s:5:"false";s:7:"_method";s:3:"PUT";}s:6:"\\u0000*\\u0000job";N;s:10:"connection";s:8:"database";s:5:"queue";N;s:15:"chainConnection";N;s:10:"chainQueue";N;s:5:"delay";N;s:7:"chained";a:0:{}}',
  ),
)  ```

**Comment by jayhof** [comment]
Hey @vicky-13 the problem you're describing is exactly what we're solving with this package.

Make sure to check out the [Configuration Section](https://github.com/joblocal/laravel-sqs-sns-subscription-queue#configuration) of the readme to see how to configure command routes according to the "Subject" or "TopicArn" fields.

**Comment by vicky-13** [comment]
@jayhof  I have done the same configuration which you have mentioned but still, they give an error like...
```
local.ERROR: Undefined index: job {"exception":"[object] (ErrorException(code: 0): Undefined index: job
```

**Comment by jayhof** [comment]
Hi @vicky-13 I'll be happy to help but please provide more information.

How did you dispatch the notification? What's the content of the notification and how did you configure the queue connector in config/queue.php?

**Comment by vicky-13** [comment]
Currently, I dispatch notification form SNS manually form AWS CLI for testing. In the notification, there will be JSON data. Queue config.

```
'sqs' => [
            'driver' => 'sqs',
            'key' => env('AWS_ACCESS_KEY_ID', 'your-public-key'),
            'secret' => env('AWS_SECRET_ACCESS_KEY', 'your-secret-key'),
            'prefix' => env('SQS_PREFIX', 'https://sqs.us-east-1.amazonaws.com/your-account-id'),
            'queue' => env('SQS_QUEUE', 'your-queue-name'),
            'region' => env('SQS_REGION', 'us-east-1'),
            'version' => env('SQS_VERSION', 'latest'),
            'routes' => [
        // you can use the "Subject" field
                'Subject' => 'App\\Jobs\\SqsJobProcess',
        // or the "TopicArn" of your SQS message
                'TopicArn' => 'App\\Jobs\\SqsJobProcess',
        // to specify which job class should handle the job
            ],
        ],
```

**Comment by jayhof** [comment]
You queue route configuration is missing. For the provided example notification:

```
{
  "Type" : "Notification",
  "MessageId" : "63a3f6b6-d533-4a47-aef9-fcf5cf758c76",
  "TopicArn" : "arn:aws:sns:us-west-2:123456789012:MyTopic",
  "Subject" : "Testing publish to subscribed queues",
  "Message" : "Hello world!",
  "Timestamp" : "2017-03-29T05:12:16.901Z",
  "SignatureVersion" : "1",
  "Signature" : "...",
  "SigningCertURL" : "...",
  "UnsubscribeURL" : "..."
}
```

The routes configuration should look like:

```php
[
  'routes' => [
     // Subject
     'Testing publish to subscribed queues' => 'App\\Jobs\\SqsJobProcess',
  ],
],
```

**Comment by vicky-13** [comment]
Will you give me a sample of SQS configuration which you have mentioned in README.MD file?
In `'TopicArn:123'` what is `123`? How SNS know which job I have to run?

**Comment by vicky-13** [comment]
@jayhof its done.

**Comment by jayhof** [comment]
@vicky-13 thanks for letting me know. Do you have any sort of suggestions on how to improve the readme to make it more clear to other users of the package?

Maybe you even want to share your example?
